[package]
name = "rust-gpu"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
burn = { version = "0.18.0", features = ["candle"] }
wasm-bindgen = "0.2"
web-sys = "0.3"
js-sys = "0.3"

[dependencies.wasm-bindgen]
version = "0.2"
features = [
  "serde-serialize",
]
